### PR TITLE
Move projects to Java 11 #672

### PR DESCRIPTION
**Pull request by claesrosell**
Moves org.eclipse.birt.viewer to JavaSE-11. Also adds javax.xml.rpc
v1.1.2 to our build since the inclusion of javax.xml.namespace in
javax.xml.rpc v1.1.0 is problematic. However, possibly faulty
Import-Package statements causes javax.xml.rpc to import another version
of javax.xml.rpc since v1.1.0 still exists in our target platform hence
this commit includes a javax.xml.rpc with modified Import-Package
statements.

### CODE REVIEW

**Comment by claesrosell** [comment]
I know that adding a modified third party bundle is not ideal but the web viewer is a mess of old legacy stuff. When we get rid of Axis1, this bundle will loose its purpose. The web viewer will, with current technologies, be hard to maintain.

**Review by wimjongman — COMMENTED** [review]
Looks good to me.

**Comment by wimjongman** [comment]
Claes, can this be submitted?

**Comment by claesrosell** [comment]
Yes

**Comment by wimjongman** [comment]
Thanks, Claes!

**Comment by hvbtup** [comment]
Probably I missed a simple manual config step in Eclipse, but for me this doesn't build in Eclipse.
I get some dozens of errors, but I think it boils down to 

Unsatisfied version constraint: 'javax.xml.rpc: 1.1.2'

for two MANIFEST.MF files in org.apache.axis/META-INF and Unsatisfied version constraint: 'javax.xml.rpc: 1.1.2'.

**Comment by claesrosell** [comment]
Have you imported the new "javax.xml.rpc" project into your workspace?

**Comment by hvbtup** [comment]
Thanks Claes, that fixed 19 of the 69 errors. I could get rid of one of them by Refresh and Clean.
I still got 49 errors then first, most of them saying that org.eclipse.birt.core.internal.util.EclipseUtil could not be imported.
These magically disappeared after 15 minutes!? Anyway, now it's working.

**Comment by wimjongman** [comment]
> Have you imported the new "javax.xml.rpc" project into your workspace?

That has the name javax.xml.rpc2 in the .project file. Was that intended? Should we not put it in our own namespace?

**Comment by claesrosell** [comment]
My intention was not to keep the project name "javax.xml.rpc2". That is probably a leftover from when I recreated the plugin so that it only contained the .jar instead of all .class files. My intention was to rename the project to "javax.xml.rpc".
I was looking at the axis and derby projects for inspiration when I created that project and they are keeping there original namespaces in their project names. Or am I missing something?

**Comment by wimjongman** [comment]
I think it is fine. Potentially it will break an already existing jacax.xml.rpc

**Pull request merged**
