### PR TITLE
Enable tests for GitHub Actions #588

### PR DESCRIPTION
**Pull request by ruspl-afed**
Switched from "mvn package" to "mvn verify".
Removed "skipTest" from arguments.

Signed-off-by: Alexander Fedorov <alexander.fedorov@arsysop.ru>

### CODE REVIEW

**Comment by wimjongman** [comment]
If we accept this PR then we will not have a green build for a while. Is this what you want?

Error:  There are test failures.
Error:  Please refer to /home/../chart/org.eclipse.birt.chart.tests/target/surefire-reports for the individual test results.

I assume the workspace is gone after the job ends?

**Comment by ruspl-afed** [comment]
> If we accept this PR then we will not have a green build for a while. Is this what you want?

Sorry, I forgot to convert this PR to draft.

First failures to investigate are:

Failed tests: 
  MonthDateFormatTest.testFormat:56 expected:<Jun[] 2013> but was:<Jun[.] 2013>
  ChartUtilTest.testStringValue:152 expected:<...5-01-22 11:56:10.125[-08]00> but was:<...5-01-22 11:56:10.125[+00]00>

Tests run: 241, Failures: 2, Errors: 0, Skipped: 0

**Comment by ruspl-afed** [comment]
@Flugtiger I think we can close this one if you can include its content to the one of your test-related PRs

**Comment by wimjongman** [comment]
Alexander, can this be closed?

**Comment by ruspl-afed** [comment]
Closing this since @wimjongman has better solution

**Pull request closed without merging**
