### PR TITLE
Replace com.lowagie.text #767

### PR DESCRIPTION
**Pull request by claesrosell**
Switched to the latest version of OpenPDF (1.3.26)

### CODE REVIEW

**Comment by hvbtup** [comment]
I saw that the CI build failed with

java.lang.NoClassDefFoundError: org/apache/batik/util/SVGConstants
	at org.eclipse.birt.chart.tests.device.render.ImageOutputBaseTest.runTest(ImageOutputBaseTest.java:101)

Is this related to this change?

**Comment by claesrosell** [comment]
Yes. This PR is not done yet. That is way it is still a draft. I have not had time to look into why yet, but I think it has to do with OpenPDF's optional dependencies to XML-graphics and PDFBox and the automatic generation of OSGI Manifest headers.

**Comment by claesrosell** [comment]
I messed this pull request up. I had it working but then I rebased against master and force pushed.
One should never do that.
Sorry, this will probably not be solved today.

**Comment by claesrosell** [comment]
Closing this PR, take a look at #814 instead

**Pull request closed without merging**
