### PR TITLE
Fix Warnings #706

### PR DESCRIPTION
**Pull request by SteveSchafer-Innovent**
Change severity level of compiler compliance and JRE compatibility to "ignore".
Change severity level of unused thrown, import, local, parameter, and private member to "ignore".

Signed-off-by: Steve Schafer <sschafer@innoventsolutions.com>

### CODE REVIEW

**Comment by hvbtup** [comment]
I'm -1 on this. 
Most of these warnings indicate possible programming errors with a non-neglectable probability of being actual errors.
Instead I think we could get rid of quite a lot of warnings by disabling all those warnings about raw types (e.g. untyped collections like List without <...>).

**Comment by claesrosell** [comment]
I am -1 on these severity changes as well. Most of these warnings should be resolved by changing the code. I am -1 on disabling warnings for untyped collections as well. It will be a lot of work but the project will be a lot more maintainable when fixed.

Warnings are our friends! They tell us what we should do to improve the code and the product.
I know that there are annoyingly many of them in this project but we shouldn't try to hide that. We should resolve them by fixing them. It will take a lot of time but until they are solved let them remain to remind us of what to do.

**Comment by wimjongman** [comment]
Steve, you can also take a project and apply the "Clean source" action to it. This can upgrade a lot of old code and will remove warnings.

e.g. fix the raw types, use modern for loops, use Lambda's, remove unused fields from the code, etc... 

Maybe you can play with that.

**Comment by SteveSchafer-Innovent** [comment]
Okay I'll see what I can do.

**Pull request closed without merging**
