### PR TITLE
Remove org.w3c.dom.events import from org.eclipse.birt.chart.device 

### PR DESCRIPTION
**Pull request by gab1one**
I was able to fix the resolution problems at startup (#757) with this change. Still need to investigate if this breaks anything.

### CODE REVIEW

**Comment by wimjongman** [comment]
Thanks, Gabriel! We will see if the tests are still running. PTL for unit tests.

**Comment by gab1one** [comment]
They looked good on my machine, but that does not necessarily mean anything in my experience.. :)

**Comment by wimjongman** [comment]
The server agrees.

**Review by wimjongman — APPROVED** [review]

**Comment by hvonbargen** [comment]
Did anyone test to generate a PDF report with SVG chart ?

**Comment by hvbtup** [comment]
It's a bit too much magic here. 

Gabriel, can you explain how you came to the conclusion that changing this one line could fix this issue?

Wim, was there a specific reason to add the version constraint '2.0.0' to the manifest file with #640?

**Comment by wimjongman** [comment]
> Wim, was there a specific reason to add the version constraint '2.0.0' to the manifest file with #640?

There was no specific reason. If there was, I can't remember.

**Comment by gab1one** [comment]
@hvbtup the debug output complained wiring conflicts with the org.w3c.dom.events package. This package is offered by the JDK and by the org.w3c.dom.events.3.0.0 bundle. That bundle is required  by the old batik bundle `org.w3c.dom.smil` which is required by the `org.apache.batik.anim` bundle.
I tried a lot of different changes, but in the end figured out, that changing this import statement was the minimal invasive change to prevent these conflicts.

**Comment by gab1one** [comment]
BTW thes chart core tests are failing locally for me, because the fragments that provide the correct runtime wiring are missing during the test run: 
- org.apache.batik.dom.birt.ext
- org.apache.batik.transcoder.birt.ext
We need to add them to the runtime of the test environment

**Comment by hvbtup** [comment]
In particular, generating a PDF report with an SVG chart and a PDF report with an SVG image (and SVG support enabled) should be tested.

Personally, I don't use the BIRT charts.  Can one of you test that?

**Pull request merged**
