### PR TITLE
Batik vulnerabilities #651

### PR DESCRIPTION
**Pull request by SteveSchafer-Innovent**
Update batik plugins to version 1.14.
    
Signed-off-by: Steve Schafer <sschafer@innoventsolutions.com>

### CODE REVIEW

**Comment by TheLaserNinja** [comment]
Good news is the build completes. The bad news is it fails during tests. :/

**Comment by wimjongman** [comment]
The tests complete normally in other builds. Is the test fail related to this change?

**Comment by ruspl-afed** [comment]
> The tests complete normally in other builds. Is the test fail related to this change?

It could be since we have something related to the images in the failure trace. I also can see another suspect entry:
```
WARNING: org/apache/batik/w3c/dom/ElementTraversal
java.lang.NoClassDefFoundError: org/apache/batik/w3c/dom/ElementTraversal
```

**Comment by SteveSchafer-Innovent** [comment]
@ruspl-afed, good catch.  It passes now that I added the jar that contains the definition of ElementTraversal.

**Pull request merged**
