### PR TITLE
Move projects to Java 11 #672

### PR DESCRIPTION
**Pull request by wimjongman**
Update .project file of rpc plugin

### CODE REVIEW

**Comment by claesrosell** [comment]
I think it makes since to apply this change.
I forgot to add javax.xml.rpc entries to the [projectSet.psf](https://github.com/eclipse/birt/blob/master/projectSet.psf) file in my PR. I guess adding the missing javax.xml.rpc entries  (both project and workingset entries) to this PR makes since. What do you think @wimjongman ?

**Comment by wimjongman** [comment]
Perfect. You can squash and merge. 

I already noticed that the oomph installer pulls in the new bundle by itself 👍

**Comment by claesrosell** [comment]
I do not have write access access yet. Atleast GitHub says: "Only those with write access to this repository can merge pull requests"

**Comment by wimjongman** [comment]
Is all the committer paperwork done? I have filed an issues with the webmasters [1]

[1] https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/861

**Pull request merged**
