### PR TITLE
SimpleResultSet.groupCalculator() called on empty RowResultSet #922

### PR DESCRIPTION
**Pull request by claesrosell**
Added a check to see if there are any data in the result set before
calling IGroupCalculator.next() on the first row.

Will try to add unit test for this.

### CODE REVIEW

**Comment by claesrosell** [comment]
I am working on a unit test for this (using data extraction api), but I do not have much time right now so it will probably take another week.

**Comment by claesrosell** [comment]
@hvbtup can you test this one with one of your data sets. This should fix the problem where "count" returns 1 for empty result sets. As a special bonus, this PR also includes a unit test for this case. This bug probably affected all aggregations but probably only had a real effect on "count".

**Comment by hvbtup** [comment]
> can you test this one with one of your data sets.

That will have to wait for some days, but I will do it.

**Comment by claesrosell** [comment]
@hvbtup: Do you think that you can test this in the coming week? This PR will hopefully solve this old issue, that you filed 8 years ago. I think that it would make a good addition to 4.10.
If you accept this fix, and it is committed, I plan to go forth with the fix for #885 (#914), which will add "access to row data in the progressive aggregator helper"

**Comment by wimjongman** [comment]
Fetch the reference to the pull request based on its ID number, creating a new branch in the process.

(#923 

$ git fetch origin pull/#923/head:BRANCHNAME

Switch to the new branch that's based on this pull request:

[main] $ git checkout BRANCHNAME
> Switched to a new branch 'BRANCHNAME'

**Comment by hvbtup** [comment]
Same error:

[ERROR] Failed to resolve target definition C:\Users\hvb\birt-master\git\birt\build\org.eclipse.birt.target\org.eclipse.birt.target.target: Could not find "org.eclipse.justj.openjdk.hotspot.jre.full.feature.group/11.0.14.v20220314-1349" in the repositories of the current location -> [Help 1]

**Review by hvbtup — APPROVED** [review]
I tested with the count-bug.rptdesign report (and with the other report there) and can confirm that this PR fixes the bug.

**Pull request merged**
