### PR TITLE
Fix extra space in docx #850

### PR DESCRIPTION
**Pull request by hvbtup**
I hope this fixes that old issue.
I'm not absolutely sure, because I have significant other changes in my DOC and DOCX emitters.

### CODE REVIEW

**Comment by hvbtup** [comment]
@wimjongman  I'm confused by GIT, so I closed this PR.
I added exactly one line to ....[emitter/docx/writer/BasicComponent.java](https://github.com/eclipse/birt/pull/851/files#diff-3c6429d05bcfb574433788a23f08af5c767402466518548ee363cd254a59dc61)

This page tells me that 1 file is changed - OK.
OTOH it says "5 commits", including https://github.com/eclipse/birt/pull/851/commits/f8b04a03f9e1bc36695ab959b0bfe203c93f965e

**Comment by wimjongman** [comment]
Can you make a test for this case so we know it will not fail again?

**Comment by hvbtup** [comment]
[birt_test-master.zip](https://github.com/eclipse/birt/files/8204753/birt_test-master.zip)

The test case used. I don't know how this could be included into the automatic CI tests.

**Comment by wimjongman** [comment]
> [birt_test-master.zip](https://github.com/eclipse/birt/files/8204753/birt_test-master.zip)
> 
> The test case used. I don't know how this could be included into the automatic CI tests.

You have to give that a try, tests are the cornerstone of quality. We can work on it together.

**Comment by wimjongman** [comment]
> @wimjongman I'm confused by GIT, so I closed this PR. I added exactly one line to ....[emitter/docx/writer/BasicComponent.java](https://github.com/eclipse/birt/pull/851/files#diff-3c6429d05bcfb574433788a23f08af5c767402466518548ee363cd254a59dc61)
> 
> This page tells me that 1 file is changed - OK. OTOH it says "5 commits", including [f8b04a0](https://github.com/eclipse/birt/commit/f8b04a03f9e1bc36695ab959b0bfe203c93f965e)

You first have to be in sync with the main repo before you make a branch. It looks like your fork is ahead.

The workflow is like this:

1. Fork BIRT
2. Make a branch in your fork
3. Make a pull request
4. Squash and merge into the main repository
5. Throw away your local branch
6. Synchronize your fork by using "Fetch Upstream" --> do not merge your own branch

image

**Comment by hvbtup** [comment]
It's not so simple unfortunately. A "historic mistake" was that when I created my repo hvbtup/birt a few years ago, I forked from flugtiger/birt instead eclipse/birt. 
It seems that GH does not allow to change that later, see https://stackoverflow.com/questions/9644046/how-to-change-the-source-of-a-github-fork  - it would require to use yet another GH account.

What I did today:
My remotes are:
origin -> hvbtup/birt
upstream -> eclipse/birt

    git checkout master
    # up to date with origin/master
    git pull upstream master
    # to include the latest changes, in particular those from Claes for my issue with CONCATENATE
    git push

    git checkout tup_main
    git pull upstream master
    git push
    # to include the latest changes also to my branch tup_main (see /hvbtup/birt/wiki/NotableDifferences)

    git checkout master
    git checkout -b "Fix_extra_space_in_DOCX_#850"
    # Then I changed BasicComponent.java

    git add engine\org.eclipse.birt.report.engine.emitter.docx\src\org
    git commit -m "..."
    git push --set-upstream origin Fix_extra_space_in_DOCX_#850
    # Several times because I thought I could keep type a single line of code without copy&paste...
    # Created this PR after the first push

Probably my master branch is not exactly the same, because the launch configurations did not work for me.

**Comment by wimjongman** [comment]
Assuming that you want your local changes in flugtiger/birt/flugtiger-master and flugtiger/birt/master to be in sync with eclipse/birt/master 

    git checkout master
    # up to date with origin/master
    git pull upstream master
    # to include the latest changes, in particular those from Claes for my issue with CONCATENATE
    git push

This did not work because your flugtiger/birt/master is still 199 commits behind.

**Comment by wimjongman** [comment]
git push

Maybe

    git push origin master

**Comment by wimjongman** [comment]
and you should make flugtiger/master the default branch in github so that you can "Fetch Upstream"

For now it does not matter because we SQUASH-and-MERGE anyway. There will be ONE new commit after that.

**Comment by hvbtup** [comment]
My fork is not flugtiger/birt, it is hvbtup/birt.

I know that Alexander Lehmann @Flugtiger did not update his fork for a long time.

git push without arguments pushes to origin master in the command sequence I used AFAIK.
I think the commands I used are correct and the reason for the problem is that I commited unrelated other changes (to the launch and target files) in my master branch which are not present in the official master branch.

**Pull request merged**
