### PR TITLE
Pull request builds 2 times #612

### PR DESCRIPTION
**Pull request by wimjongman**
Fixed to only build on push when pushed to master

### CODE REVIEW

**Review by ruspl-afed — APPROVED** [review]
Thanks @wimjongman, looks reasonable. 
Let's see how it will work for subsequent pushes to the source branch of PR

**Comment by wimjongman** [comment]
Maybe we don't have to build when pushed to master because we should never push directly. It is too late then anyway because the change has already been merged. The main build will pick up the build and deploy it.

(the main build is green by the way 💪)

**Comment by ruspl-afed** [comment]
> Maybe we don't have to build when pushed to master

I would keep it for a while. I have an impression that it is triggered after PR merged to master.

**Comment by wimjongman** [comment]
We can keep it but it is not very useful. Deployment build is here:

https://ci.eclipse.org/birt/

**Comment by ruspl-afed** [comment]
> but it is not very useful

For me it is a kind of proof that "build from sources" works in `master`

> Deployment build is here:

Thank you for the link!

**Pull request merged**
