### PR TITLE
Review ReportLauncherUtils.java: #671

### PR DESCRIPTION
**Pull request by claesrosell**
Removed unused and 16 year old dead code.

Almost all the scary stuff in this class was unused if the dead code in getAutoStartPlugins() was removed. That if(true) statement was introduced a looong time ago.

### CODE REVIEW

**Comment by wimjongman** [comment]
Looks good to me. Are you done?

**Comment by claesrosell** [comment]
Yes, I am done.

**Comment by ruspl-afed** [comment]
+1 from my side

**Review by ruspl-afed — APPROVED** [review]

**Comment by wimjongman** [comment]
Thanks!

**Pull request merged**
