### PR TITLE
Added image data URL handling to the excel cell content handler (#1237)

### PR DESCRIPTION
**Pull request by speckyspooky**
The enhancement make the option of data url accessible for excel output which is located into text element based on image tag.

### CODE REVIEW

**Review by hvbtup — APPROVED** [review]

**Comment by speckyspooky** [comment]
Can I start the merge of the pull request?

**Comment by hvbtup** [comment]
> Can I start the merge of the pull request?

Yes.

**Comment by wimjongman** [comment]
Hey Thomas, since you are now a commiter, you can squash and merge the PR. Please use Squash and merge whenever merging so we do not get all the developer commits in.

The workflow is to first ask for a review. Then if you have a positive review, you can SQ&M.

**Comment by speckyspooky** [comment]
Thanks Henning &  Wim! The merge is done with SQ&M.

**Comment by wimjongman** [comment]
Congratulations on your first merge. I hope many more will follow. 🎉

**Pull request merged**
