### PR TITLE
Reformat all code

### PR DESCRIPTION
**Pull request by SteveSchafer-Innovent**
Reformat all code #635

All code reformatted after .settings files were imported.

Signed-off-by: Steve Schafer <sschafer@innoventsolutions.com>

### CODE REVIEW

**Comment by ruspl-afed** [comment]
I wonder what the origin of the conflicts is?

**Comment by wimjongman** [comment]
> I wonder what the origin of the conflicts is?

We submitted new code and Steve did not pull it beforehand.

Steve, please resolve these conflicts.

**Comment by ruspl-afed** [comment]
I think this one should be merged ahead of all others, otherwise conflict resolution will be just endless

**Comment by wimjongman** [comment]
@SteveSchafer-Innovent the build is failing because of a java version issue on project org.eclipse.bird.build please move jre up to 1.8

**Comment by SteveSchafer-Innovent** [comment]
@wimjongman not sure where to do that.  The root pom already has requireJavaVersion 1.8 and I don't see requireJavaVersion in any other poms, although I do see 1.5 in some ant build scripts.

**Comment by ruspl-afed** [comment]
+1
we need this one to unblock a lot of work

**Comment by wimjongman** [comment]
Thanks, Steve.

**Pull request merged**
