### PR TITLE
Report viewer failing again. #649

### PR DESCRIPTION
**Pull request by claesrosell**
Please review

### CODE REVIEW

**Comment by hvbtup** [comment]
This is great!
The preview is working. I tested this from within Exclipse, not with the Maven build.
The SLF4J still not working. Did you commit the changes to make it work as well?

**Comment by wimjongman** [comment]
Thanks, Claes. Awesome work.

The local dev viewer is working but the product does not at this moment. It is failing with a 503.

Looking at the differences between my workspace and the product I see the following missing jetty items (in the product):

* org.eclipse.birt.jetty.overlay_4.9.0.qualifier
* org.eclipse.jetty.annotations_10.0.6
* org.eclipse.jetty.jmx_10.0.6
* org.eclipse.jetty.schemas_4.0.3  <-- ???
* org.eclipse.jetty.servlet-api_4.0.6 <--

There are other differences, but let's add these first.

**Comment by wimjongman** [comment]
I have found the issue with the product. It seems that the extra entries in the web.xml which were removed by Claes, are automatically generated during the build.

Removing the generated data from the web.xml solves the previewer and allows to generate all formats.

The web.xml to change is here: plugins/org.eclipse.birt.report.viewer_4.9.0.v202111221047/birt/WEB-INF

**Comment by claesrosell** [comment]
I will need to get the build environment up and running to solve this. I will try to do that tonight.
When I last tried that, three years ago, it was the precompilation of jsp that made me give up. I guess that it is needed for some of the deployment scenarios of the viewer though.

**Comment by claesrosell** [comment]
I have tested this with the "org.eclipse.birt.designer-win32.win32.x86_64" product and it works for me.

**Comment by wimjongman** [comment]
Claes, you are marvelous. Thank you!!

**Pull request merged**
