### PR TITLE
Null pointer exception using count aggregate #885

### PR DESCRIPTION
**Pull request by claesrosell**
Added special case for ScriptConstants.ROW_NUM_KEYWORD in org.eclipse.birt.data.engine.executor.aggregation.ProgressiveAggregationHelper$JSColumnBindingRow as seen in org.eclipse.birt.data.engine.script.JSResultSetRow also made some clean up.

@hvbtup, can you do some hardcore testing on this? This seems like a small fix, and I think that it is done correctly, but one never knows.

### CODE REVIEW

**Comment by wimjongman** [comment]
Can you make a test for it, Claes?

**Comment by claesrosell** [comment]
I can make a try.

**Comment by hvbtup** [comment]
Well, at least it's not failing anymore. But I'm not sure if the result is correct. I'll explain in #885.

**Comment by hvbtup** [comment]
Can you explain fd342f7dd15d3a963175ab43f10979c62bc08b57?

**Comment by claesrosell** [comment]
The problem is that the Accumulator.onRow(Object[] args) is called even if the resultset is empty.
It is the groupCalculator that is causing this faulty call, and since it seems like an error to call the groupCalculator when there are no data in the resultset I looked on the behaviour of how the final row in the resultset is treated. (see doNext() in SimpleResultSet).
This is not neccesserily right though, since this.groupCalculator.next(0); seems to have been called from prepareFirstRow() even before you reported https://bugs.eclipse.org/bugs/show_bug.cgi?id=438257 . I will continue my investigation. The commit was more of a "unit test run" since my local engine tests does not work.

Do you know the exact version this stopped working?

**Comment by wimjongman** [comment]
The build is working again. Seems to be a temp error.

**Comment by claesrosell** [comment]
This PR now only contains the fix for the NPE when using row.__rownum.
For the original problem described in https://bugs.eclipse.org/bugs/show_bug.cgi?id=438257, see #922

**Comment by claesrosell** [comment]
I am working on a unit test for this (using data extraction api), but I do not have much time right now so it will probably take another week.

**Comment by wimjongman** [comment]
@claesrosell can we take this for 4.10 which I plan to release soon?

**Review by wimjongman — APPROVED** [review]
Looks good to me! Thanks, Claes.

**Pull request merged**
