### PR TITLE
Add debug options to all-in-one launch config

### PR DESCRIPTION
**Pull request by gab1one**
This shows the resolver working during startup and allows us to find the cause for slow startup times

### CODE REVIEW

**Comment by wimjongman** [comment]
I have approved the workflow run. Binaries are available in the Action after the build.

**Comment by wimjongman** [comment]
Gabriel, please sign the eclipse ECA. When you have signed it we can take in your code. Please make sure to use the same email address as the github email

https://www.eclipse.org/legal/ECA.php

**Comment by gab1one** [comment]
Done 👍🏾

**Review by wimjongman — APPROVED** [review]

**Comment by wimjongman** [comment]
🙏🎈✨🎉

Thank you for your first commit @gab1one, may there be many more!

**Pull request merged**
